# Generated by Django 6.1.1 on 2026-09-05 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        choices=[
                            (1, "😢 بد"),
                            (2, "😕 نه\u200cچندان"),
                            (3, "😐 معمولی"),
                            (4, "🙂 خوب"),
                            (5, "😊 عالی"),
                        ],
                        help_text="وضعیت احساسی خود را انتخاب کنید",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="حال",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً: خوشحال، خسته، پرانرژی، ناراحت",
                        max_length=50,
                        null=True,
                        verbose_name="برچسب",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="اگر دوست دارید بیشتر توضیح دهید",
                        null=True,
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت حال",
                "verbose_name_plural": "ثبت\u200cهای حال",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="checkins_mo_user_id_47ac61_idx",
                    ),
                    models.Index(fields=["score"], name="checkins_mo_score_b48aa3_idx"),
                ],
            },
        ),
    ]
