# Generated by Django 6.1 on 2026-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='tag',
            field=models.CharField(default='alpha'),
            preserve_default=False,
        ),
    ]
